# Generated by Django 5.1.5 on 2025-01-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='sakshi@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='sakshi@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
